const data = [
  {
    id: 'item-01',
    image: process.env.PUBLIC_URL + '/images/sub_product01.jpg',
    title: '생활한복 나시 원피스',
    desc: '한벌옷 / 원피스',
    price: '107,100원',
    price_two: 107100,
  },
  {
    id: 'item-02',
    image: process.env.PUBLIC_URL + '/images/sub_product02.jpg',
    title: '호운 트렌치코트',
    desc: '한벌 옷 / 외투',
    price: '197,600원',
    price_two: 197600,
  },
  {
    id: 'item-03',
    image: process.env.PUBLIC_URL + '/images/sub_product03.jpg',
    title: '한복형 크롭 자켓',
    desc: '한벌옷 / 외투',
    price: '64,000원',
    price_two: 64000,
  },
  {
    id: 'item-04',
    image: process.env.PUBLIC_URL + '/images/sub_product04.jpg',
    title: '저고리 자켓',
    desc: '한벌 옷 / 외투',
    price: '93,000원',
    price_two: 93000,
  },
  {
    id: 'item-05',
    image: process.env.PUBLIC_URL + '/images/sub_product05.jpg',
    title: '데님 셔켓 저고리 세트',
    desc: '한벌옷 / 상·하의 세트',
    price: '239,000원',
    price_two: 239000,
  },
  {
    id: 'item-06',
    image: process.env.PUBLIC_URL + '/images/sub_product06.jpg',
    title: '색동 노방 양면 뷔스티에',
    desc: '한벌옷 / 원피스',
    price: '88,200원',
    price_two: 88200,
  },
  {
    id: 'item-07',
    image: process.env.PUBLIC_URL + '/images/sub_product07.jpg',
    title: '한아 방령 저고리',
    desc: '한벌옷 / 외투',
    price: '110,000원',
    price_two: 110000,
  },
  {
    id: 'item-08',
    image: process.env.PUBLIC_URL + '/images/sub_product08.jpg',
    title: '민화 모시 볼레로',
    desc: '한벌옷 / 외투',
    price: '40,250원',
    price_two: 40250,
  },
  {
    id: 'item-09',
    image: process.env.PUBLIC_URL + '/images/sub_product09.jpg',
    title: '은방울꽃 닮은 저고리와 트임 스커트',
    desc: '한벌옷 / 상·하의 세트',
    price: '98,800원',
    price_two: 98800,
  },
  {
    id: 'item-10',
    image: process.env.PUBLIC_URL + '/images/sub_product10.jpg',
    title: '리버서블 아우터 양털자켓',
    desc: '한벌옷 / 외투',
    price: '88,000원',
    price_two: 88000,
  },
  {
    id: 'item-11',
    image: process.env.PUBLIC_URL + '/images/sub_product11.jpg',
    title: '저고리 투피스, 저고리&스커트 2종',
    desc: '한벌옷 / 상·하의 세트',
    price: '138,000원',
    price_two: 138000,
  },
  {
    id: 'item-12',
    image: process.env.PUBLIC_URL + '/images/sub_product12.jpg',
    title: '16세기 저고리 재킷',
    desc: '한벌옷 / 외투',
    price: '210,000원',
    price_two: 210000,
  },
];

export default data;